Added the sriov_ib project
Mellanox/sriov_cni_ci pull request #22
Opened 2020-04-20 17:32 UTC by AbdYsn

Added the IPoIB CNI CI project to the scripts.

2020-04-20 17:33 UTC, AbdYsn commented
@moshe010

2020-04-20 17:41 UTC, moshe010 requested changes
make sure you use the common code

2020-04-20 17:41 UTC, moshe010 commented on sriov_ib_cni_install.sh
> +function configure_multus {
is this duplicate to the common code?

2020-04-21 09:47 UTC, AbdYsn commented
@moshe010 added the code to set the exclusive mode to the install script.

2020-04-21 16:23 UTC, moshe010 requested changes

2020-04-21 16:23 UTC, moshe010 commented on sriov_ib_cni_stop.sh
> +kill $(ps -ef |grep local-up-cluster.sh|grep $WORKSPACE|awk '{print $2}')
why this is not in command methods

2020-04-22 14:52 UTC, AbdYsn commented
/retest

2020-04-22 15:58 UTC, moshe010 approved these changes

2020-04-22 15:59 UTC, merged