Modified the ib CNI CI test pod image
Mellanox/sriov_cni_ci pull request #35
Opened 2020-07-05 13:58 UTC by AbdYsn

Changed the image of the testing pods of the IB CNI CI project
from the default mellanox/centos_7_4_mofed_4_2_1_2_0_0_60 to
mmdh/rping-test. This is needed because this image have problems
with the rping on the latest distro (centos 8.1) and kernel (5.8-rc3).

2020-07-05 13:58 UTC, AbdYsn commented
@moshe010

2020-07-05 14:05 UTC, AbdYsn commented
/retest

2020-07-05 16:42 UTC, moshe010 requested changes

2020-07-05 16:42 UTC, moshe010 commented on ib_cni_test.sh
> +test_pod_image='mmdh/rping-test'
let push image with rping to Mellanox docker hub

2020-07-06 05:23 UTC, AbdYsn commented
/retest

2020-07-06 08:31 UTC, moshe010 approved these changes

2020-07-06 08:31 UTC, merged